name: Build and Deploy React App to EC2

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from GitHub repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Node.js environment and install dependencies
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Use the Node.js version required for your React app

    - name: Install dependencies
      run: npm install

    # Step 3: Build the React application
    - name: Build React App
      run: npm run build

    # Step 4: Rsync the build files to the EC2 instance
    - name: Deploy to EC2 via Rsync
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}       # EC2 IP address or hostname (stored as a secret)
        EC2_USER: ${{ secrets.EC2_USER }}       # EC2 username (e.g., 'ubuntu', stored as a secret)
        EC2_KEY: ${{ secrets.EC2_KEY }}         # Private SSH key (stored as a secret)
        EC2_PATH: ${{ secrets.EC2_DEPLOY_PATH }}       # Deployment path on EC2 (e.g., '/var/www/html/')
      run: |
        sudo apt-get update && sudo apt-get install -y rsync  # Install rsync
        rsync -avz -e "ssh -i $EC2_KEY -o StrictHostKeyChecking=no" \
          ./dist/ $EC2_USER@$EC2_HOST:$EC2_PATH  # Sync the build folder to EC2

    
